application:
  title: "eCommerce REST API"
  version: "1.0"

server:
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.jks  # Adjust to your keystore location
#    key-store-password: changeit  # Use your actual password
#    key-alias: royalmail
#    key-store-type: JKS # Use the alias for your key entry # Specify the alias of the key entry
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://mr-vape-db.cvagu0gwmi5q.eu-west-2.rds.amazonaws.com/sb-ecommerce-dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root  # !exposed
    password: Malikjee123  # !exposed
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  messages:
    basename: validation-messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  stripe:
    api:
      secret-key: "pk_test_51NgU8ZKmvY8D2mUALsoAnz00j94YOrP4IMZRQ65cLYz8emEvURQFRcYWEPG73RQBOJIUln0dcZ9wKP4Kbzr6VpWz00gqg9EANG" # Replace with your actual secret key
      publishable-key: "pk_test_51NgU8ZKmvY8D2mUALsoAnz00j94YOrP4IMZRQ65cLYz8emEvURQFRcYWEPG73RQBOJIUln0dcZ9wKP4Kbzr6VpWz00gqg9EANG" # Replace with your actual publishable key
